In [25]:
import pandas as pd
import numpy as np

创建：1.纵向列表 2.纵向字典 3.纵向Series

In [3]:
df_obj = pd.DataFrame({'科目代码':['1001','1002','2202'],
                       '科目名称':['现金','yinhang','yingfu']})
df_obj

   科目代码     科目名称
0  1001       现金
1  1002  yinhang
2  2202   yingfu

In [ ]:
df_obj2 = pd.DataFrame({'daima':{'5':'1001','1':'1020','4':'2201'},
                        'mingcheng':{'5':'xianjin','1':'yinhang','4':'yingfu'},
                        'd':{'5':'01','1':'02','4':'03'}})
df_obj2.loc['5','d']
df_obj2.loc[['1','4','5'],'daima':'mingcheng']
df_obj2.iloc[0,1]
df_obj2.iloc[0:2]

'01'

In [48]:
data = np.array([('wangdachui',4000),
                 ('linling',5000),
                 ('niuyun',6000)])
frame = pd.DataFrame(data,index = range(1,4),columns=['name','pay'])
frame

         name   pay
1  wangdachui  4000
2     linling  5000
3      niuyun  6000

In [28]:
print('(1)')
print(frame.index)
print(frame.columns)

(1)
RangeIndex(start=1, stop=4, step=1)
Index(['name', 'pay'], dtype='object')

In [36]:
print('(2)')
frame.name
frame.pay
frame.loc[0:2,'pay']

(2)

1    4000
2    5000
Name: pay, dtype: object

In [39]:
print('(3)')
frame.pay.min()
frame[frame.pay >= '5000']

(3)

      name   pay
2  linling  5000
3   niuyun  6000

In [49]:
frame['name'] = 'admin'
#frame.drop('pay',axis=1)
del frame['pay']
frame

    name
1  admin
2  admin
3  admin